---
title: "data explore"
author: "Wanying Ma"
date: "12/18/2018"
output: pdf_document
header-includes:
- \usepackage{bm}
- \usepackage{amsmath}
- \usepackage{booktabs} 
- \usepackage{pgfplots} 
- \usepackage{pgfplotstable} 
- \usepackage{multirow}
- \usepackage{bm}
- \usepackage{amsmath}
- \usepackage{booktabs} 
- \usepackage{pgfplots} 
- \usepackage{pgfplotstable} 
- \usepackage{multirow}
- \usepackage{bm}
- \newcommand{\Real}{\mathbb{R}}
- \newcommand{\dom}{{\bf dom}\,}
- \newcommand{\Tra}{^{\sf T}} % Transpose
- \newcommand{\Inv}{^{-1}} % Inverse
- \def\vec{\mathop{\rm vec}\nolimits}
- \def\sweep{\mathop{\rm sweep}\nolimits}
- \newcommand{\diag}{\mathop{\rm diag}\nolimits}
- \newcommand{\tr}{\operatorname{tr}} % Trace
- \newcommand{\epi}{\operatorname{epi}} % epigraph
- \newcommand{\V}[1]{{\bm{\mathbf{\MakeLowercase{#1}}}}} % vector
- \newcommand{\VE}[2]{\MakeLowercase{#1}_{#2}} % vector element
- \newcommand{\Vn}[2]{\V{#1}^{(#2)}} % n-th vector
- \newcommand{\Vtilde}[1]{{\bm{\tilde \mathbf{\MakeLowercase{#1}}}}} % vector
- \newcommand{\Vhat}[1]{{\bm{\hat \mathbf{\MakeLowercase{#1}}}}} % vector
- \newcommand{\VtildeE}[2]{\tilde{\MakeLowercase{#1}}_{#2}} % vector element
- \newcommand{\M}[1]{{\bm{\mathbf{\MakeUppercase{#1}}}}} % matrix
- \newcommand{\ME}[2]{\MakeLowercase{#1}_{#2}} % matrix element
- \newcommand{\Mtilde}[1]{{\bm{\tilde \mathbf{\MakeUppercase{#1}}}}} % matrix
- \newcommand{\Mhat}[1]{{\bm{\hat \mathbf{\MakeUppercase{#1}}}}} % matrix
- \newcommand{\Mcheck}[1]{{\bm{\check \mathbf{\MakeUppercase{#1}}}}} % matrix
- \newcommand{\Mbar}[1]{{\bm{\bar \mathbf{\MakeUppercase{#1}}}}} % matrix
- \newcommand{\Mn}[2]{\M{#1}^{(#2)}} % n-th matrix
---
## Access to data files
```{r , echo=FALSE, warning=FALSE}
library(dplyr)
library(refund)
# there are 195 players
files <- list.files(path="/Users/mawanying/Dropbox/Luo_Jarek_YC/csv_voxelwise", pattern="*.csv", full.names=FALSE, recursive=FALSE)

subname <- gsub(pattern=".csv", replacement="", files)
# there are 27 tracts 
tractnames = c("ar_l",  "ar_r",  "atr_l", "atr_r", "cgc_l", "cgc_r", "cgh_l", "cgh_r", "cst_l", "cst_r","fma",   
               "fmi", "ifo_l", "ifo_r", "ilf_l", "ilf_r", "mcp",  
               "ml_l",  "ml_r",  "ptr_l", "ptr_r", "slf_l", "slf_r", "str_l" ,"str_r", "unc_l", "unc_r")
# 200 quantiles we want to use
den.quantiles = seq(0.25, 99.75, length=200)
load("/Users/mawanying/Dropbox/Luo_Jarek_YC/summary_data.Rdata")
load("/Users/mawanying/Dropbox/Luo_Jarek_YC/alldata_qdt.Rdata") #dim(alldata_qdt): 21052x203
```

## Add group index, merge with player information, keep only football players, delete duplicates between 3 groups, and construct group index.
```{r}
#############################################################################
######################### players information table #########################
######################### create group index ################################
######################### delete duplicates #################################
#############################################################################

player.info <- read.csv("/Users/mawanying/Dropbox/Luo_Jarek_YC/MRI_Injury_Description_03OCT18_All_Concussions_ForLuo.csv") #player.info is 136x9
basic.info <- player.info %>% select(SUBJECTSTUDYNUM, INJURYSPORTVARSITY, CONTACTSPORTQGID, NONCONTACTSPORTQGID) #basic.info is 136x4
football.info <- basic.info %>% filter(INJURYSPORTVARSITY=='Football') #football.info is 88x4
#first in second
d1 <- football.info$SUBJECTSTUDYNUM %in% football.info$CONTACTSPORTQGID
#first in third
d2 <- football.info$SUBJECTSTUDYNUM %in% football.info$NONCONTACTSPORTQGID
#second in first
d3 <- football.info$CONTACTSPORTQGID %in% football.info$SUBJECTSTUDYNUM
#second in third
d4 <- football.info$CONTACTSPORTQGID %in% football.info$NONCONTACTSPORTQGID
#third in first
d5 <- football.info$NONCONTACTSPORTQGID %in% football.info$SUBJECTSTUDYNUM
#third in second
d6 <- football.info$NONCONTACTSPORTQGID %in% football.info$CONTACTSPORTQGID
dupli <- cbind(d1, d2, d3, d4, d5, d6) #88x6
football.noDup <- football.info[rowSums(dupli)<1, ] # football.noDup is 53x4

#############################################################################
############## construct group index for football players ###################
##############      group1: SUBJECTSTUDYNUM                 ############
##############      group2: CONTACTSPORTQGID                ############
##############      group3: NONCONTACTSPORTQGID             ############
#############################################################################
group1 <- unique(as.character(football.noDup$SUBJECTSTUDYNUM))     #SUBJECTSTUDYNUM 43x1
group2 <- unique(as.character(football.noDup$CONTACTSPORTQGID))    #CONTACTSPORTQGID 43x1
group3 <- unique(as.character(football.noDup$NONCONTACTSPORTQGID)) #NONCONTACTSPORTQGID 43x1

# after merge, alldata_fb will have 28 players in group 1, 30players in group 2, 28 players in group 3
#############################################################################
alldata.player <- as.character(alldata$player) #21052x1
alldata.fb.player <- alldata.player %in% c(group1, group2, group3) #indicator vector: 9280x1
groupindex <- c()
for(i in alldata.player[alldata.fb.player]){
  if(i %in% group1){
    groupindex <- c(groupindex, 1)
  }
  if(i %in% group2){
    groupindex <- c(groupindex, 2)
  }
  if(i %in% group3){
    groupindex <- c(groupindex, 3)
  }
}

addgroupindex <- function(data, football_index, groupindex){
  fbdata <- data[football_index, ]
  data.fb <- fbdata %>% mutate(group=groupindex)
  return(data.fb)
}
alldata.fb <- addgroupindex(alldata, alldata.fb.player, groupindex) #9280x204
alldata.fb_qdt <- addgroupindex(alldata_qdt, alldata.fb.player, groupindex) #9280x204

colnames(alldata.fb)[4:203] <- colnames(alldata.fb_qdt)[4:203] <- paste0("den", 1:200)
#table(alldata.fb$group)
#1    2    3 
#3016 3240 3024 
# there are 86 different players in total for alldata.fb
#alldata_fb will have 28 players in group 1, 30players in group 2, 28 players in group 3
```

## cluster
### Using equally-spaced density(no transformation), as well as quantile-density transformation of density $-log(f(Q(t)))$
```{r}
m.tract.cluster <- function(data, iter){
  # data: input dataset
  # m: measurement, in {"FA", "MD", "Da", "Dr"}
  # t: tract
  t <- as.character(para[iter, 1])
  m <- as.character(para[iter, 2])
  data.tm <- data %>% filter(tract==t, measure==m) #86x204
  den.tm <- select(data.tm, den1:den200)    #86x200
  den.tm <- den.tm - as.vector(rep(1, dim(den.tm)[1])) %*% t(colMeans(den.tm))
  den.fpca <- refund::fpca.face(data.matrix(den.tm), center = TRUE, argvals = (1:200)/200, knots = 7, pve = 0.95, p = 5, lambda = NULL)
  den.score <- den.fpca$scores/sqrt(dim(den.tm)[2]) #86x5
  den.cluster <- kmeans(den.score, centers = 3)
 
permute <- function(vec, p1, p2, p3){
  for(i in 1:length(vec)){
    if(vec[i]==1){
      vec[i] <- p1
    }else{
      if(vec[i]==2){vec[i] <- p2}else{
        vec[i] <- p3
      }
    }
  }
  return(vec)  
}


  perm1 <- permute(den.cluster$cluster, 1,2,3)
  perm2 <- permute(den.cluster$cluster, 1,3,2)
  perm3 <- permute(den.cluster$cluster, 2,1,3)
  perm4 <- permute(den.cluster$cluster, 2,3,1)
  perm5 <- permute(den.cluster$cluster, 3,1,2)
  perm6 <- permute(den.cluster$cluster, 3,2,1)
  misrate <- min(sum(perm1!=data.tm$group)/length(data.tm$group),
      sum(perm2!=data.tm$group)/length(data.tm$group),
      sum(perm3!=data.tm$group)/length(data.tm$group),
      sum(perm4!=data.tm$group)/length(data.tm$group),
      sum(perm5!=data.tm$group)/length(data.tm$group),
      sum(perm6!=data.tm$group)/length(data.tm$group))
  data.tm.comb = cbind(data.tm, den.score)
  return(list(misrate=misrate,
              data.tm.comb=data.tm.comb,
              den.fpca=den.fpca))
}

m.tract.cluster2 <- function(data, iter){
  # data: input dataset
  # m: measurement, in {"FA", "MD", "Da", "Dr"}
  # t: tract
  t <- as.character(para[iter, 1])
  m <- as.character(para[iter, 2])
  
  data.tm <- data %>% filter(tract==t, measure==m, group != 3) #86x204
  den.tm <- select(data.tm, den1:den200)    #86x200
  #den.tm <- den.tm - as.vector(rep(1, dim(den.tm)[1])) %*% t(colMeans(den.tm))
  den.fpca <- refund::fpca.face(data.matrix(den.tm), center = TRUE, argvals = (1:200)/200, knots = 7, pve = 0.95, p = 5, lambda = NULL)
  den.score <- den.fpca$scores/sqrt(dim(den.tm)[2]) #86x5
  den.cluster <- kmeans(den.score, centers = 2)
  permute <- function(vec, p1, p2){
    for(i in 1:length(vec)){
      if(vec[i]==1){vec[i] <- p1}else{vec[i] <- p2}
    }
    return(vec)
  }
  perm1 <- permute(den.cluster$cluster, 1,2)
  perm2 <- permute(den.cluster$cluster, 2,1)
  misrate <- min(sum(perm1!=data.tm$group)/length(data.tm$group),
                 sum(perm2!=data.tm$group)/length(data.tm$group))
  data.tm.comb = cbind(data.tm, den.score)
  return(list(misrate=misrate,
              data.tm.comb=data.tm.comb,
              den.fpca=den.fpca))
}

```


##cluster results
```{r, echo=FALSE}
para <- expand.grid(tractnames, c("FA","MD","Da","Dr"))
## equally spaced density 3 clusters 
misrate_FA <- sapply(1:27, function(x) m.tract.cluster(alldata.fb, x)$misrate)
misrate_MD <- sapply(28:54, function(x) m.tract.cluster(alldata.fb, x)$misrate)
misrate_Da <- sapply(55:81, function(x) m.tract.cluster(alldata.fb, x)$misrate)
misrate_Dr <- sapply(82:108, function(x) m.tract.cluster(alldata.fb, x)$misrate)
cat("Misrate for 3 clusters:\n")
cat("No transformation: FA\n")
misrate_FA[order(misrate_FA)[1:5]]
cat("No transformation: MD\n")
misrate_MD[order(misrate_MD)[1:5]]
cat("No transformation: Da\n")
misrate_Da[order(misrate_Da)[1:5]]
cat("No transformation: Dr\n")
misrate_Dr[order(misrate_Dr)[1:5]]
cat("Corresponding tracts:\n")
cat("FA:\n")
tractnames[order(misrate_FA)[1:5]]
cat("MD:\n")
tractnames[order(misrate_MD)[1:5]]
cat("Da:\n")
tractnames[order(misrate_Da)[1:5]]
cat("Dr:\n")
tractnames[order(misrate_Dr)[1:5]]

## use quantile-density transformation corresponding to quantiles 3 clusters
misrate_FA_qdt <- sapply(1:27, function(x) m.tract.cluster(alldata.fb_qdt, x)$misrate)
misrate_MD_qdt <- sapply(28:54, function(x) m.tract.cluster(alldata.fb_qdt, x)$misrate)
misrate_Da_qdt <- sapply(55:81, function(x) m.tract.cluster(alldata.fb_qdt, x)$misrate)
misrate_Dr_qdt <- sapply(82:108, function(x) m.tract.cluster(alldata.fb_qdt, x)$misrate)

cat("Misrate for 3 clusters:\n")
cat("Quantile-density transformation: FA\n")
misrate_FA_qdt[order(misrate_FA_qdt)[1:5]]
cat("Quantile-density transformation: MD\n")
misrate_MD_qdt[order(misrate_MD_qdt)[1:5]]
cat("Quantile-density transformation: Da\n")
misrate_Da_qdt[order(misrate_Da_qdt)[1:5]]
cat("Quantile-density transformation: Dr\n")
misrate_Dr_qdt[order(misrate_Dr_qdt)[1:5]]

cat("Corresponding tracts:\n")
cat("FA:\n")
tractnames[order(misrate_FA_qdt)[1:5]]
cat("MD:\n")
tractnames[order(misrate_MD_qdt)[1:5]]
cat("Da:\n")
tractnames[order(misrate_Da_qdt)[1:5]]
cat("Dr:\n")
tractnames[order(misrate_Dr_qdt)[1:5]]


```
## only cluster first two groups
```{r, echo=FALSE}
# 2 cluster density
misrate_FA2 <- sapply(1:27,  function(x) m.tract.cluster2(alldata.fb, x)$misrate)
misrate_MD2 <- sapply(28:54, function(x) m.tract.cluster2(alldata.fb, x)$misrate)
misrate_Da2 <- sapply(55:81, function(x) m.tract.cluster2(alldata.fb, x)$misrate)
misrate_Dr2 <- sapply(82:108,function(x) m.tract.cluster2(alldata.fb, x)$misrate)
cat("Misrate for 2 clusters:\n")
cat("No transformation: FA\n")
misrate_FA2[order(misrate_FA2)[1:5]]
cat("No transformation: MD\n")
misrate_MD2[order(misrate_MD2)[1:5]]
cat("No transformation: Da\n")
misrate_Da2[order(misrate_Da2)[1:5]]
cat("No transformation: Dr\n")
misrate_Dr2[order(misrate_Dr2)[1:5]]

cat("Corresponding tracts:\n")
cat("FA:\n")
tractnames[order(misrate_FA2)[1:5]]
cat("MD:\n")
tractnames[order(misrate_MD2)[1:5]]
cat("Da:\n")
tractnames[order(misrate_Da2)[1:5]]
cat("Dr:\n")
tractnames[order(misrate_Dr2)[1:5]]


#use quantile-density transformation corresponding to quantiles 2 clusters
misrate_FA_qdt2 <- sapply(1:27,  function(x) m.tract.cluster2(alldata.fb_qdt, x)$misrate)
misrate_MD_qdt2 <- sapply(28:54, function(x) m.tract.cluster2(alldata.fb_qdt, x)$misrate)
misrate_Da_qdt2 <- sapply(55:81, function(x) m.tract.cluster2(alldata.fb_qdt, x)$misrate)
misrate_Dr_qdt2 <- sapply(82:108,function(x) m.tract.cluster2(alldata.fb_qdt, x)$misrate)
cat("Misrate for 2 clusters:\n")
cat(" FA\n")
misrate_FA_qdt2[order(misrate_FA_qdt2)[1:5]]
cat("qd transformation: MD\n")
misrate_MD_qdt2[order(misrate_MD_qdt2)[1:5]]
cat("qd transformation: Da\n")
misrate_Da_qdt2[order(misrate_Da_qdt2)[1:5]]
cat("qd transformation: Dr\n")
misrate_Dr_qdt2[order(misrate_Dr_qdt2)[1:5]]

cat("Corresponding tracts:\n")
cat("Quantile-density transformation: FA\n")
tractnames[order(misrate_FA_qdt2)[1:5]]
cat("Quantile-density transformation: MD\n")
tractnames[order(misrate_MD_qdt2)[1:5]]
cat("Quantile-density transformation: Da\n")
tractnames[order(misrate_Da_qdt2)[1:5]]
cat("Quantile-density transformation: Dr\n")
tractnames[order(misrate_Dr_qdt2)[1:5]]
```
## Visualized variation modes
```{r}
#fb_score <- lapply(1:dim(para)[1], function(x) m.tract.cluster2(alldata.fb, x)$data.tm.comb)
#fb_score <- do.call(rbind, fb_score) #9280x209
#fb_scorefpca <- lapply(1:dim(para)[1], function(x) m.tract.cluster2(alldata.fb, x)$den.fpca)

var_mode <- function(data, m, t, title, qd){
loc_m <- which(para[,2]==m)
loc <- loc_m[which(para[loc_m,1]==t)] #loc in the para that is tract=='unc_r', measure=='Da'
fb_scorefpca <- lapply(loc, function(x) m.tract.cluster2(data, x)$den.fpca)

eigenf <- fb_scorefpca[[1]]$efunctions*sqrt(200)
eigens <- fb_scorefpca[[1]]$scores/sqrt(200)
mean <- fb_scorefpca[[1]]$mu
pc1_score_q <- quantile(eigens[,1], c(0.1, 0.25, 0.75, 0.95))
modes1 <- cbind(t(as.vector(pc1_score_q)%*% t(eigenf[,1])) + mean, mean) #200x5
pc2_score_q <- quantile(eigens[,2], c(0.1, 0.25, 0.75, 0.95))
modes2 <- cbind(t(as.vector(pc2_score_q)%*% t(eigenf[,2])) + mean, mean) #200x5
tran_back <- function(den.tran.y, den.quantiles){
  thetax <- sum((head(exp(den.tran.y), -1)+tail(exp(den.tran.y), -1))/2*(diff(den.quantiles/100)[1]))

  tranback_x <- sapply(1:200, function(x){
    sum((head(exp(den.tran.y)[1:x], -1)+tail(exp(den.tran.y)[1:x],-1))/2*(diff(den.quantiles/100)[1]))/thetax
  })
  tranback_y <- exp(-den.tran.y)*thetax
  return(list(tranback_x= tranback_x,
              tranback_y=tranback_y,
              thetax=thetax)) 
}

if(qd==0){
matplot(den.quantiles/100, modes1, main=paste0("1st PC modes, ",title, "\n tract:", t, ", measure:", m),
        xlab="t", ylab=expression(psi(t)), 
        col=c("red","pink","green","blue", "black"), type="l", 
        lty=c(1,1,1,1,1), lwd=c(1,1,1,1,1.5))
abline(h=0, col="grey", lwd=1, lty=2)
legend("topleft", c(expression(alpha[1]), expression(alpha[2]), expression(alpha[3]), expression(alpha[4]), expression(alpha[5])), col=c("red","pink","black","green","blue"), lty=c(1,1,1,1,1), lwd=c(1,1,1.5,1,1), cex=0.8, bty='n')

matplot(den.quantiles/100, modes2, main=paste0("1st PC modes, ",title, "\n tract:", t, ", measure:", m),
        xlab="t", ylab=expression(psi(t)), 
        col=c("red","pink","green","blue", "black"), type="l",
        lty=c(1,1,1,1,1), lwd=c(1,1,1,1,1.5))
abline(h=0, col="grey", lwd=1, lty=2)
legend("topleft", c(expression(alpha[1]), expression(alpha[2]), expression(alpha[3]), expression(alpha[4]), expression(alpha[5])), col=c("red","pink","black","green","blue"), lty=c(1,1,1,1,1), lwd=c(1,1,1.5,1,1), cex=0.8, bty='n')

}
if(qd==1){
tran_den <- lapply(data.frame(modes1), function(x){tran_back(x, den.quantiles)}) 
plot(tran_den[[1]]$tranback_x, tran_den[[1]]$tranback_y, type="l",main=paste0("1st PC modes, ",title, "\n tract:", t, ", measure:", m), col="red", ylim=c(0, max(c(tran_den[[1]]$tranback_y, tran_den[[2]]$tranback_y,
                                tran_den[[3]]$tranback_y, tran_den[[4]]$tranback_y,
                                tran_den[[5]]$tranback_y))),
     xlab="x", ylab='f(x)')
abline(h=0, col="grey", lwd=1, lty=2)
lines(tran_den[[2]]$tranback_x, tran_den[[2]]$tranback_y, type="l", col="pink")
lines(tran_den[[3]]$tranback_x, tran_den[[3]]$tranback_y, type="l", col="green")
lines(tran_den[[4]]$tranback_x, tran_den[[4]]$tranback_y, type="l", col="blue")
lines(tran_den[[5]]$tranback_x, tran_den[[5]]$tranback_y,col="black", lwd=1.5)
legend("topleft", c(expression(alpha[1]), expression(alpha[2]), expression(alpha[3]), expression(alpha[4]), expression(alpha[5])), col=c("red","pink","black","green","blue"), lty=c(1,1,1,1,1), lwd=c(1,1,1.5,1,1), cex=0.8, bty='n')

tran_den2 <- lapply(data.frame(modes2), function(x){tran_back(x, den.quantiles)}) 
plot(tran_den2[[1]]$tranback_x, tran_den2[[1]]$tranback_y, type="l",main=paste0("2nd PC modes, ",title, "\n tract:", t, ", measure:", m),
     xlab="x", ylab=expression(psi^{-1}(x)), 
     col="red", ylim=c(0, max(c(tran_den2[[1]]$tranback_y, tran_den2[[2]]$tranback_y, 
                                tran_den2[[3]]$tranback_y, tran_den2[[4]]$tranback_y,
                                tran_den2[[5]]$tranback_y))))
abline(h=0, col="grey", lwd=1, lty=2)
lines(tran_den2[[2]]$tranback_x, tran_den2[[2]]$tranback_y, type="l", col="pink")
lines(tran_den2[[3]]$tranback_x, tran_den2[[3]]$tranback_y, type="l", col="green")
lines(tran_den2[[4]]$tranback_x, tran_den2[[4]]$tranback_y, type="l", col="blue")
lines(tran_den2[[5]]$tranback_x, tran_den2[[5]]$tranback_y, col="black", lwd=1.5)
legend("topleft", c(expression(alpha[1]), expression(alpha[2]), expression(alpha[3]), expression(alpha[4]), expression(alpha[5])), col=c("red","pink","black","green","blue"), lty=c(1,1,1,1,1), lwd=c(1,1,1.5,1,1), cex=0.8, bty='n')

}
}

locM <- which.min(c(min(misrate_FA_qdt2), min(misrate_MD_qdt2), min(misrate_Da_qdt2), min(misrate_Dr_qdt2)))
minM <- c('FA', 'MD', 'Da', 'Dr')[locM]
minT <- c(as.character(tractnames)[order(misrate_FA_qdt2)[1]], 
          as.character(tractnames)[order(misrate_MD_qdt2)[1]],
          as.character(tractnames)[order(misrate_Da_qdt2)[1]],
          as.character(tractnames)[order(misrate_Dr_qdt2)[1]])[locM]

var_mode(alldata.fb, m=minM, t=minT, title='Ordinary FPCA', qd=0)

var_mode(alldata.fb_qdt, m=minM, t=minT, title='log quantile-density transformation', qd=1)


```
